board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.board, name='board'),
    path('add/', views.add, name="add"),
    path('list/', views.list, name='list'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/', views.delete, name="delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'))
]

board/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Board(models.Model):
    title = models.CharField(max_length=50)
    writer = models.CharField(max_length=30)
    content = models.TextField()
    regdate = models.DateTimeField(auto_now = timezone.now)
    readcount = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title}. {self.writer}({self.readcount})"
    
    def incrementReadCount(self):
        self.readcount += 1
        self.save()

board/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Board

# Create your views here.

def board(request):
    return render(request, 'board/board.html')



def list(request):
    board_list = Board.objects.all()
    context = {
        'board_list' : board_list,
    }
    return render(request, 'board/list.html', context)


def detail(request, id):
    board = Board.objects.get(id=id)
    board.incrementReadCount()
    context = {
        'board' : board,
    }
    return render(request, 'board/detail.html', context)


def update(request, id): 
    board = Board.objects.get(id=id)
    if request.method == 'GET':
        context = {
            'board' : board,
        }
        return render(request, 'board/update.html', context)
    
    elif request.method == 'POST':
        board_title = request.POST['title']
        board_writer = request.POST['writer']
        board_content = request.POST['content']
        Board.objects.filter(id=id).update(title=board_title, writer=board_writer, content=board_content)
        return HttpResponseRedirect(reverse('board:detail', args=(board.id,))) # args 값 주는 (== url의 id)
    
    
def delete(request, id):
    board = Board.objects.get(id=id)
    if request.method == 'GET':
        context = {
            'board' : board,
        }
        return render(request, 'board/delete.html', context)
        
    elif request.method == 'POST':
        board.delete()
        return HttpResponseRedirect(reverse('board:list'))
    
    
def add(request):
    if request.method == "GET":
        return render(request, 'board/add.html')
    
    elif request.method == 'POST':
        add_title = request.POST['title']
        add_writer = request.POST['writer']
        add_content = request.POST['content']
        Board.objects.create(title=add_title, writer=add_writer, content=add_content)
        return HttpResponseRedirect(reverse('board:list'))

board/templates/board/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add</title>
</head>
<body>
    <form action="{% url 'board:add' %}" method="post">
        {% csrf_token %}
        <p>Title : <input type="text" name="title" placeholder="제목"></p>
        <p>Writer: <input type="text" name="writer" placeholder="작성자"></p>
        Content<br>
        <textarea name="content" rows="7" cols="50" placeholder="내용 작성"></textarea>
        <br>
        <input type="submit" value="등록">
    </form>
</body>
</html>

board/templates/board/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Board</title>
</head>
<body>
    <br>
    <ul>
        <li><a href="{% url 'board:list' %}"><input type='submit' value="목록"></a></li> <br>
        <li><a href="{% url 'board:add' %}"><input type='submit' value="등록"></a></li>
    </ul>
</body>
</html>

board/templates/board/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
</head>
<body>
    <br>
    <p>선택한 게시글 [ {{ board.title }}, {{ board.writer }} ]를 정말 삭제하시겠습니까?</p>
    <form method="post">
        {% csrf_token %}
        <a href ="{% url 'board:delete' board.id %}"><button>삭제</button></a><br>
    </form>
    <a href ="{% url 'board:list' %}">취소</a>
</body>
</html>

board/templates/board/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>
<body>
    <br>
    <hr>
    <table style="width:500px">
		<tr>
			<td>글 내용 날짜</td>
			<td>{{ board.regdate }}</td>		
		</tr>
		<tr>
			<td>조회수</td>
			<td>{{ board.readcount }}</td>		
		</tr>
        <tr>
			<td>작성자</td>
			<td>{{ board.writer }}</td>		
		</tr>
        <tr>
			<td>제목</td>
			<td>{{ board.title }}</td>		
		</tr>
        <tr>
			<td>내용</td>
			<td>{{ board.content }}</td>		
		</tr>
	</table>
    <hr>
    <form method='post'>
        {% csrf_token %}
        <a href="{% url "board:update" board.id %}">수정</a><br>
        <a href="{% url 'board:delete' board.id %}">삭제</a><br>
        <a href="{% url 'board:list' %}">목록보기</a>
    </form>

</body>
</html>

board/templates/board/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List</title>
    <style>
		table, th, td { border: 1px solid black}
	</style>
</head>
<body>
    <table style="width:300px">
		<tr style="background-color:lightgrey">
			<th>번호</th>
			<th>제목</th>		
			<th>작성자</th>
			<th>조회수</th>
		</tr>
        {% for board in board_list%}
        <tr style="text-align:center">   
            <td><b>{{ board.id }}</b></td>
			<td><a href="{% url 'board:detail' board.id %}">{{ board.title }}</a></td>		
			<td>{{ board.writer }}</td>
			<td>{{ board.readcount }}</td>
        </tr>
        {% endfor %}
	</table>
	<br>
	<a href="{% url 'board:add' %}"><button>글 등록</button></a>
</body>
</html>

board/templates/board/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>
</head>
<body>
    <form action="{% url 'board:update' board.id %}" method='post'>
        {% csrf_token %}
        <p>Title : <input type="text" name="title" value={{ board.title }}></p>
        <p>Writer: <input type="text" name="writer" value={{ board.writer }}></p>
        Content<br>
        <textarea name="content" rows="7" cols="50">{{ board.content }}</textarea>
        <br>
        <input type="submit" value="수정">
    </form>
</body>
</html>